/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProfileLazyImport = createFileRoute('/profile')()
const OrderListLazyImport = createFileRoute('/order-list')()
const OrderDetailsLazyImport = createFileRoute('/order-details')()
const CreditCardLazyImport = createFileRoute('/credit-card')()
const CartLazyImport = createFileRoute('/cart')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ProfileLazyRoute = ProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const OrderListLazyRoute = OrderListLazyImport.update({
  path: '/order-list',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order-list.lazy').then((d) => d.Route))

const OrderDetailsLazyRoute = OrderDetailsLazyImport.update({
  path: '/order-details',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order-details.lazy').then((d) => d.Route))

const CreditCardLazyRoute = CreditCardLazyImport.update({
  path: '/credit-card',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/credit-card.lazy').then((d) => d.Route))

const CartLazyRoute = CartLazyImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cart.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartLazyImport
      parentRoute: typeof rootRoute
    }
    '/credit-card': {
      id: '/credit-card'
      path: '/credit-card'
      fullPath: '/credit-card'
      preLoaderRoute: typeof CreditCardLazyImport
      parentRoute: typeof rootRoute
    }
    '/order-details': {
      id: '/order-details'
      path: '/order-details'
      fullPath: '/order-details'
      preLoaderRoute: typeof OrderDetailsLazyImport
      parentRoute: typeof rootRoute
    }
    '/order-list': {
      id: '/order-list'
      path: '/order-list'
      fullPath: '/order-list'
      preLoaderRoute: typeof OrderListLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CartLazyRoute,
  CreditCardLazyRoute,
  OrderDetailsLazyRoute,
  OrderListLazyRoute,
  ProfileLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cart",
        "/credit-card",
        "/order-details",
        "/order-list",
        "/profile"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cart": {
      "filePath": "cart.lazy.tsx"
    },
    "/credit-card": {
      "filePath": "credit-card.lazy.tsx"
    },
    "/order-details": {
      "filePath": "order-details.lazy.tsx"
    },
    "/order-list": {
      "filePath": "order-list.lazy.tsx"
    },
    "/profile": {
      "filePath": "profile.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
